#-------------------------------
# General Site Settings
title: Rasine
logo: # You can add own logo. For example '/images/logo.png'.
description: Hi, my name is Rasine. I’m an artist and a designer based in Abuja. I am passionate about drawing, design and computational art with GANs.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://rasine.art" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  avatar: '/images/rasine.jpg'
  name: Rasine
  job: Artist & Designer

social:
#- {icon: "ion-logo-twitter", link: "https://twitter.com"}
#- {icon: "ion-logo-facebook", link: "https://facebook.com"}
#- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/rasynee"}
- {icon: "ion ion-logo-github", link: "https://github.com/Rasynee"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Featured Slider
slider: false # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.


#-------------------------------
# Contact Settings
contact:
  email: ukenerasing@gmail.com # Add your email for contact form
  description: Looking for an artist, designer, or just wanting to get in touch? I'll be happy to hear from you. # Add a description of your form

# NOTE
# Bonso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: rasynee # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
#mailchimp-text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
#mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed